export const GAME = {
  maxPlayers: 8,
  serverHz: 30,
  clientHz: 60,
  networkSnapshotHz: 20,
  roundSeconds: 180,
  playerSpeed: 7.5,
  playerRadius: 0.55,
  projectileRadius: 0.28,
  bananaRadius: 0.5,
  dodgeSeconds: 0.24,
  dodgeCooldownSeconds: 1.05,
  dodgeSpeedMultiplier: 2.25,
  pickupRadius: 0.65,
  pickupRespawnSeconds: 5,
  tomatoAmmoStart: 3 as number,
  tomatoAmmoMax: 5,
  bananaAmmoStart: 1 as number,
  bananaAmmoMax: 2,
  objectiveRadius: 3,
} as const;
